### PR TITLE
Updates dev dependencies and TypeScript 2.9 compat

### LINKED ISSUE #88: waxeye does not compile with TS2.9
I'm getting something like this (with a slightly outdated version of waxeye):

```
waxeye/src/javascript/waxeye.ts:11:31 - error TS2322: Type 'string | number' is not assignable to type 'string'.
  Type 'number' is not assignable to type 'string'.

11   public parse(input: string, start: string = this.start): AST|ParseError {
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~
waxeye/src/javascript/waxeye.ts:384:55 - error TS2345: Argument of type '(string | number)[]' is not assignable to parameter of type 'string[]'.
  Type 'string | number' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

384       evalNext(env[start].exp, 0, [], new RawError(0, [start], [], start), []));
                                                          ~~~~~~~
waxeye/src/javascript/waxeye.ts:655:28 - error TS2345: Argument of type 'string | number' is not assignable to parameter of type 'string'.
  Type 'number' is not assignable to type 'string'.

655             return new AST(start, asts.reverse());
                               ~~~~~
waxeye/src/javascript/waxeye.ts:668:32 - error TS2345: Argument of type 'string | number' is not assignable to parameter of type 'string'.
  Type 'number' is not assignable to type 'string'.

668                 return new AST(start, asts.reverse());
                                   ~~~~~

```

### PR DESCRIPTION
**Pull request by glebm**
Staying up with the times

Fixes #88

### CODE REVIEW

**Comment by orlandohill** [comment]
Looks great. Thanks!
